### ISSUE TITLE
Bug Token-Erstellung in SymconBotvac/BotvacControl/SymconBotvac/BotvacControl/module.php

### ISSUE THREAD

**Issue by crandler** [traxanos/SymconBotvac#1]
Beim Erstellen des Tokens liefert in meinem Fall die Vorwerk-API den Statuscode 201, was zu einem Invalid Response führt. 

Workaround in Zeile 112 der module.php:
        } elseif ($status != '200' && $status != '201') {

**Comment by traxanos** [comment]
Danke übernehme ich später... Lg 

Von meinem iPhone gesendet

**Comment by traxanos** [comment]
Habe ich übernommen.
